name: 📝 Pull Request Template
description: PR 생성 시 관련 이슈, 원인, 처리과정, 테스트 결과 등을 작성해 주세요
title: "[PR] 제목을 입력해 주세요"
body:
  - type: input
    id: related-issues
    attributes:
      label: 🔗 관련 이슈
      description: 관련된 이슈 번호를 입력해 주세요 (예: #123)
      placeholder: "#123"
    validations:
      required: false

  - type: textarea
    id: issue-cause
    attributes:
      label: 🐞 이슈 원인
      description: 어떤 문제 때문에 이 PR을 작성하게 되었나요?
      placeholder: |
        예: 로그인 시 세션이 만료되어도 로그아웃 처리가 되지 않음
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 🔧 변경 사항 / 처리 과정
      description: 이 PR에서 어떤 작업을 했는지 구체적으로 작성해 주세요
      placeholder: |
        - 세션 만료 시 자동 로그아웃 기능 추가
        - API `/auth/refresh-token` 구현
        - 기존 코드 리팩토링
    validations:
      required: true

  - type: checkboxes
    id: tests
    attributes:
      label: ✅ 테스트 결과
      description: PR을 테스트한 결과를 체크해 주세요
      options:
        - label: 세션 만료 후 자동 로그아웃 확인
        - label: 신규 API 정상 응답 확인
        - label: 기존 테스트 케이스 통과 (`./gradlew test`)
        - label: 기타 테스트 완료

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 스크린샷 / 기타 참고 사항 (선택)
      description: UI 변경 시 스크린샷을 첨부하거나 참고자료 링크를 추가해 주세요
      placeholder: |
        - 이미지: ![스크린샷](url)
        - 참고 링크: [디자인 명세서](https://link.to/spec)

  - type: textarea
    id: reviewer-notes
    attributes:
      label: 🙏 리뷰어에게 하고 싶은 말
      description: 리뷰어가 중점적으로 봐줬으면 하는 부분을 적어주세요
      placeholder: |
        예: 예외 처리 방식이 괜찮은지 확인 부탁드립니다.
