spring:
  application:
    name: CheongyakJipsa
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    basename: messages
jipsa:
  security:
    jwt:
      secret-key: test1234test1234test1234test1234
      minute: 10
      algorithm: hs256
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
      force-request: true
