spring:
  application:
    name: CheongyakJipsa
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    basename: messages/member,messages/security
    encoding: UTF-8

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
      force-request: true

jwt:
  access-token-validity: 1800000
  refresh-token-validity: 1209600000
  profile-verification-token-validity: 300000
