spring:
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(AMZvbT7nA3DJJIbafQx85SLCwuTMW12JKQ2cUocFh38OiYxJMRA/T359lVHN/vKCoS2zCMCEXCw=)
    username: ENC(2Y0z4iiVdltYrrSkJ0GlMQ==)
    password: ENC(hYV7HjzY/AfsRCbDXznJYE0nrmsVL/2evvMiTnejKauO2XA6I2T59EzI5IH7HblI)
  jpa:
    show-sql: true
dataApi:
  applyHome:
    apiKey: 3Ef3hiJShpTGdcBWDIEoucZHTET/stBz1mlvGX4TeVKjIXdRxffm2sLXBmNK7ZNJKJNnFw+3t8StJOrO/3Grjw==
