spring:
  application:
    name: CheongyakJipsa
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    basename: messages
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
      force-request: true
jasypt:
  encryptor:
    password: ${JASYPT_KEY:g22PKJqfCnc-4fQ.}
springdoc:
  api-docs:
    path: /v3/api-docs
