spring:
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://138.2.117.145:3306/cheongyak
    username: jibsa
    password: 2z!2H*3fgcc6jxnyJC3WLxqJ
  jpa:
    show-sql: true
