spring:
  application:
    name: CheongyakJipsa
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    basename: messages
  mail:
    host: smtp.gmail.com
    port: 587
    username: leunj87511@gmail.com
    password: nacg ccms smzz fkny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true
      force-request: true
jasypt:
  encryptor:
    password: ${JASYPT_KEY:g22PKJqfCnc-4fQ.}
springdoc:
  api-docs:
    path: /v3/api-docs
